import { StyleSheet } from "react-native";
import { COLORS } from "./Constant";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: COLORS.bgBeige,
    padding: 20,
    paddingBottom: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  containerimg: {
    flexGrow: 1,
    width: "100%",
    height: "100%",
    //backgroundColor: COLORS.bgBeige,
    padding: 20,
    paddingBottom: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    width: "70%",
    resizeMode: "contain" as const,
    fontSize: 24,
    fontWeight: "bold" as const,
    color: COLORS.verdeoscuro,
    marginBottom: 20,
    textAlign: "center" as const,
  },
  formContainer: {
    width: "100%",
    marginTop: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  label: {
    fontSize: 16,
    color: COLORS.black,
    marginBottom: 5,
    textAlign: "center" as const,
  },
  input: {
    height: 50,
    width: "90%",
    backgroundColor: COLORS.white,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderColor: COLORS.borderGray,
    borderWidth: 1,
    textAlign: "center" as const,
  },
  errorText: {
    color: "red",
    marginBottom: 15,
    textAlign: "center" as const,
  },
  button: {
    backgroundColor: COLORS.verdeoscuro,
    paddingVertical: 15,
    paddingHorizontal: 60,
    borderRadius: 8,
    marginVertical: 20,
    justifyContent: "center" as const,
    alignItems: "center" as const,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold" as const,
    textAlign: "center" as const,
  },
  footerContainer: {
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    marginTop: 10,
  },
  footerText: {
    fontSize: 16,
    color: COLORS.black,
    textAlign: "center" as const,
  },
  registerText: {
    fontSize: 16,
    color: COLORS.verdeoscuro,
    fontWeight: "bold" as const,
    textDecorationLine: "underline" as const,
    marginLeft: 5,
    textAlign: "center" as const,
  },
});
